Repository SubnauticaModding/Nautilus, pull requests merged in 2018-07, with the labels that each got.

#35 [2.0] README.md changes
  README.md
Labels: 2.0, CHANGES

#36 [2.0] Method renames and more overloads
  SMLHelper/Handlers/CraftDataHandler.cs
  SMLHelper/Handlers/CraftTreeHandler.cs
  SMLHelper/Handlers/KnownTechHandler.cs
Labels: 2.0, CHANGES

#42 2.0.OSubMarin - Additional checked for PreRegistered TechTypes and CraftTreeTypes
  SMLHelper/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/Utility/ExtBannedIdManager.cs
Labels: 2.0, CHANGES

#41 External ban list for enum registering
  SMLHelper/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/Utility/ExtBannedIdManager.cs
Labels: 2.0, CHANGES

#45 2.0NodeHandling - Reworked node handling, now nodes are changed individually instead of…
  SMLHelper/Crafting/NodeFamily.cs
  SMLHelper/Handlers/CraftTreeHandler.cs
  SMLHelper/Legacy/Patchers/CraftTreePatcher.cs
  SMLHelper/Patchers/CraftTreePatcher.cs
  SMLHelper/SMLHelper.csproj
Labels: 2.0, FIXES

#48 2.0 add group add after
  SMLHelper/Handlers/CraftDataHandler.cs
  SMLHelper/Legacy/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
Labels: NEW STUFF
