Repository SubnauticaModding/Nautilus, pull requests merged in 2019-02, with the labels that each got.

#75 PDAScanPatching - New Handler and Patcher
  SMLHelper/Handlers/CraftDataHandler.cs
  SMLHelper/Handlers/PdaHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/LanguagePatcher.cs
  SMLHelper/Patchers/PdaPatcher.cs
  SMLHelper/SMLHelper.csproj
Labels: Status: Completed, Type: Enhancement

#74 Sort mods options list
  SMLHelper/Handlers/OptionsPanelHandler.cs
  SMLHelper/Options/ModOptions.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
Labels: Status: Completed, Type: Enhancement

#76 SafeLegacyTechData
  SMLHelper/Legacy/Patchers/CraftDataPatcher.cs
  SMLHelper/mod.json
Labels: Status: Review Needed, Type: Bug

#79 My take on the log levels
  SMLHelper/Logger.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
Labels: Status: Review Needed, Type: Enhancement

#78 Add different logging levels
  SMLHelper/Assets/Craftable.cs
  SMLHelper/Assets/Spawnable.cs
  SMLHelper/Initializer.cs
  SMLHelper/Legacy/Patchers/CraftDataPatcher.cs
  SMLHelper/Legacy/Patchers/CraftTreePatcher.cs
  SMLHelper/Legacy/Patchers/DevConsolePatcher.cs
  SMLHelper/Legacy/Patchers/KnownTechPatcher.cs
  SMLHelper/Legacy/Patchers/LanguagePatcher.cs
  SMLHelper/Logger.cs
  SMLHelper/MonoBehaviours/Fixer.cs
  SMLHelper/Options/Utility/Validator.cs
  SMLHelper/Patchers/BioReactorPatcher.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/CraftTreePatcher.cs
  SMLHelper/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Patchers/DevConsolePatcher.cs
  SMLHelper/Patchers/ItemsContainerPatcher.cs
  SMLHelper/Patchers/LanguagePatcher.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/Patchers/PdaPatcher.cs
  SMLHelper/Patchers/PrefabDatabasePatcher.cs
  SMLHelper/Patchers/ResourcesPatcher.cs
  SMLHelper/Patchers/SpritePatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/Utility/ExtBannedIdManager.cs
  SMLHelper/Utility/ImageUtils.cs
  SMLHelper/Utility/KeyCodeUtils.cs
Labels: Status: In Progress, Type: Enhancement

#77 CraftDataDupChecks - Check for duplicate keys
  SMLHelper.Tests/Properties/AssemblyInfo.cs
  SMLHelper.Tests/SMLHelper.Tests.csproj
  SMLHelper.Tests/SelfCheckingDictionaryTests.cs
  SMLHelper.Tests/packages.config
  SMLHelper.sln
  SMLHelper/Handlers/BioReactorHandler.cs
  SMLHelper/Handlers/CraftDataHandler.cs
  SMLHelper/Legacy/Patchers/CraftDataPatcher.cs
  SMLHelper/Logger.cs
  SMLHelper/MonoBehaviours/Fixer.cs
  SMLHelper/Patchers/BioReactorPatcher.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/SelfCheckingDictionary.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/Utility/PatchUtils.cs
Labels: Type: Bug, Type: Enhancement
