Repository SubnauticaModding/Nautilus, pull requests merged in 2019-01, with the labels that each got.

#68 ItemsContainer Patcher
  SMLHelper/Initializer.cs
  SMLHelper/Patchers/InventoryPatcher.cs
  SMLHelper/Patchers/ItemsContainerPatcher.cs
  SMLHelper/SMLHelper.csproj
Labels: FIXES

#67 Use implicitly-typed variables instead of var
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Crafting/ModCraftTreeFamily.cs
  SMLHelper/Crafting/TechData.cs
  SMLHelper/Handlers/PrefabHandler.cs
  SMLHelper/Handlers/SpriteHandler.cs
  SMLHelper/Handlers/TechTypeHandler.cs
  SMLHelper/Legacy/CustomCraftTreeFamily.cs
  SMLHelper/Legacy/Patchers/CraftDataPatcher.cs
  SMLHelper/Legacy/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Legacy/Utility.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/CraftTreePatcher.cs
  SMLHelper/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Patchers/DevConsolePatcher.cs
  SMLHelper/Patchers/KnownTechPatcher.cs
  SMLHelper/Patchers/LanguagePatcher.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/Patchers/PrefabDatabasePatcher.cs
  SMLHelper/Patchers/ResourcesPatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/Utility/ImageUtils.cs
  SMLHelper/Utility/PatchUtils.cs
  SMLHelper/Utility/ReflectionHelper.cs
Labels: Status: Completed, Type: Maintenance

#70 Language overrides
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Assets/Spawnable.cs
  SMLHelper/Crafting/ModCraftTreeFamily.cs
  SMLHelper/Crafting/NodeFamily.cs
  SMLHelper/Handlers/CraftTreeHandler.cs
  SMLHelper/Handlers/LanguageHandler.cs
  SMLHelper/Handlers/TechTypeHandler.cs
  SMLHelper/Legacy/CustomCraftTab.cs
  SMLHelper/Legacy/CustomCraftTreeFamily.cs
  SMLHelper/Legacy/Patchers/CraftTreePatcher.cs
  SMLHelper/Legacy/Patchers/LanguagePatcher.cs
  SMLHelper/Legacy/Patchers/TechTypePatcher.cs
  SMLHelper/Patchers/LanguagePatcher.cs
Labels: Status: Completed, Type: Enhancement

#71 Change mod options and add example mod
  Example mod/Example mod.csproj
  Example mod/Mod.cs
  Example mod/Properties/AssemblyInfo.cs
  Example mod/mod.json
  SMLHelper.sln
  SMLHelper/Initializer.cs
  SMLHelper/Options/ChoiceModOption.cs
  SMLHelper/Options/KeybindModOption.cs
  SMLHelper/Options/ModOptions.cs
  SMLHelper/Options/SliderModOption.cs
  SMLHelper/Options/ToggleModOption.cs
  SMLHelper/Options/Utility/Validator.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/ImageUtils.cs
  SMLHelper/Utility/KeyCodeUtils.cs
  SMLHelper/Utility/PatchUtils.cs
  SMLHelper/Utility/PlayerPrefsExtra.cs
  SMLHelper/Utility/PrefabUtils.cs
  SMLHelper/Utility/SaveUtils.cs
  SMLHelper/mod.json
Labels: Status: Completed, Type: Enhancement

#73 Check if the mods tab already exists before adding it
  SMLHelper/Patchers/OptionsPanelPatcher.cs
Labels: Status: Completed, Type: Maintenance
