Repository SubnauticaModding/Nautilus, pull requests merged in 2019-04, with the labels that each got.

#86 ItemAction - Patcher and Handler for Middle Click Actions
  SMLHelper/Handlers/ItemActionHandler.cs
  SMLHelper/Handlers/PDAHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Interfaces/IItemActionHandler.cs
  SMLHelper/Patchers/ItemActionPatcher.cs
  SMLHelper/Patchers/ItemsContainerPatcher.cs
  SMLHelper/Patchers/PdaPatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/SelfCheckingDictionary.cs
Labels: Status: Completed, Type: Enhancement

#88 Integration of FishFramework
  SMLHelper/Assets/CustomFish.cs
  SMLHelper/Assets/CustomFishPrefab.cs
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Handlers/CustomFishHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Patchers/CustomFishPatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/PrefabUtils.cs
Labels: Type: Enhancement

#93 TooltipPatcher - Extra tooltip information
  Dependencies/QModInstaller.dll
  SMLHelper/Handlers/TechTypeHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Logger.cs
  SMLHelper/Patchers/LanguagePatcher.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/Patchers/TooltipPatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/Utility/ExtBannedIdManager.cs
  SMLHelper/Utility/ReflectionHelper.cs
Labels: Status: Completed, Type: Enhancement

#94 Small cleanup and easier obtaining of MethodInfos in patchers
  SMLHelper/Assets/Craftable.cs
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Crafting/ModCraftTreeFamily.cs
  SMLHelper/Crafting/TechData.cs
  SMLHelper/Patchers/BioReactorPatcher.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/CraftTreePatcher.cs
  SMLHelper/Patchers/CraftTreeTypePatcher.cs
  SMLHelper/Patchers/DevConsolePatcher.cs
  SMLHelper/Patchers/ItemActionPatcher.cs
  SMLHelper/Patchers/ItemsContainerPatcher.cs
  SMLHelper/Patchers/KnownTechPatcher.cs
  SMLHelper/Patchers/LanguagePatcher.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/Patchers/PdaPatcher.cs
  SMLHelper/Patchers/PrefabDatabasePatcher.cs
  SMLHelper/Patchers/ResourcesPatcher.cs
  SMLHelper/Patchers/TechTypePatcher.cs
  SMLHelper/Patchers/TooltipPatcher.cs
Labels: Status: Completed, Type: Maintenance
