Repository SubnauticaModding/Nautilus, pull requests merged in 2020-03, with the labels that each got.

#133 Auto save dynamic patching
  Dependencies/BelowZero/QModInstaller.dll
  Dependencies/BelowZero/UnityEngine.UI.dll
  Dependencies/Subnautica/QModInstaller.dll
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Handlers/CraftDataHandler_Subnautica.cs
  SMLHelper/Handlers/IngameMenuHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Interfaces/IIngameMenuHandler.cs
  SMLHelper/Patchers/CraftDataPatcher.cs
  SMLHelper/Patchers/CraftDataPatcher_BelowZero.cs
  SMLHelper/Patchers/CraftDataPatcher_Subnautica.cs
  SMLHelper/Patchers/IngameMenuPatcher.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/Utility/EnumCacheManager.cs
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Status: Review Needed, Type: Enhancement

#130 Mod options update
  Dependencies/0Harmony.dll
  Dependencies/BelowZero/UnityEngine.TextRenderingModule.dll
  Dependencies/LitJson.dll
  Dependencies/Newtonsoft.Json.dll
  Dependencies/Subnautica/UnityEngine.TextRenderingModule.dll
  SMLHelper/Options/ChoiceModOption.cs
  SMLHelper/Options/KeybindModOption.cs
  SMLHelper/Options/ModOptions.cs
  SMLHelper/Options/SliderModOption.cs
  SMLHelper/Options/ToggleModOption.cs
  SMLHelper/Options/Utility/Validator.cs
  SMLHelper/Patchers/OptionsPanelPatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/PatchUtils.cs
Labels: Status: Review Needed, Type: Enhancement, Type: Maintenance

#120 Play .wav files globally - AudioUtils class
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/AudioUtils.cs
Labels: Type: Enhancement

#140 Added simple KeyCode utility methods that behave identically like Gam…
  SMLHelper/Utility/KeyCodeUtils.cs
Labels: Priority: Low, Type: Enhancement
