Repository SubnauticaModding/Nautilus, pull requests merged in 2020-09, with the labels that each got.

#184 Asynchronous loading for ModPrefab
  SMLHelper/Assets/CustomFabricator.cs
  SMLHelper/Assets/ModPrefab.cs
  SMLHelper/Assets/ModPrefabCache.cs
  SMLHelper/Assets/ModPrefabRequest.cs
  SMLHelper/Patchers/PrefabDatabasePatcher.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/Utility/PatchUtils.cs
Labels: Type: Maintenance

#185 Update README to reflect QMM4, BepInEx and HarmonyX
  .github/README.md
Labels: Type: Maintenance

#173 Attribute-based config and mod options
  Example mod/Example mod.csproj
  Example mod/Mod.cs
  Example mod/mod.json
  SMLHelper.sln
  SMLHelper/Handlers/OptionsPanelHandler.cs
  SMLHelper/Interfaces/IModOptionAttribute.cs
  SMLHelper/Interfaces/IModOptionEventArgs.cs
  SMLHelper/Interfaces/IModOptionEventAttribute.cs
  SMLHelper/Interfaces/IOptionsPanelHandler.cs
  SMLHelper/Json/ConfigFile.cs
  SMLHelper/Json/ConfigFileAttribute.cs
  SMLHelper/Options/Attributes/ButtonAttribute.cs
  SMLHelper/Options/Attributes/ChoiceAttribute.cs
  SMLHelper/Options/Attributes/ConfigFileMetadata.cs
  SMLHelper/Options/Attributes/IgnoreMemberAttribute.cs
  SMLHelper/Options/Attributes/KeybindAttribute.cs
  SMLHelper/Options/Attributes/MemberInfoMetadata.cs
  SMLHelper/Options/Attributes/MenuAttribute.cs
  SMLHelper/Options/Attributes/ModOptionAttribute.cs
  SMLHelper/Options/Attributes/ModOptionAttributeMetadata.cs
  SMLHelper/Options/Attributes/ModOptionEventAttribute.cs
  SMLHelper/Options/Attributes/OnChangeAttribute.cs
  SMLHelper/Options/Attributes/OnGameObjectCreatedAttribute.cs
  SMLHelper/Options/Attributes/OptionsMenuBuilder.cs
  SMLHelper/Options/Attributes/SliderAttribute.cs
  SMLHelper/Options/Attributes/ToggleAttribute.cs
  SMLHelper/Options/ButtonModOption.cs
  SMLHelper/Options/ChoiceModOption.cs
  SMLHelper/Options/KeybindModOption.cs
  SMLHelper/Options/ModOptionTooltip.cs
  SMLHelper/Options/ModOptions.cs
  SMLHelper/Options/SliderModOption.cs
  SMLHelper/Options/ToggleModOption.cs
  SMLHelper/Patchers/TooltipPatcher.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Type: Enhancement

#188 SMLHelper 2.8.5 - Hotfix for `FloatConverter` globalisation issue.
  SMLHelper/Json/Converters/FloatConverter.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/Utility/JsonUtils.cs
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: Medium, Type: Bug

#189 Custom Console Commands API
  Dependencies/BelowZero.exp/Unity.TextMeshPro.dll
  Dependencies/BelowZero.exp/UnityEngine.UI.dll
  Dependencies/Subnautica.exp/UnityEngine.CoreModule.dll
  Dependencies/Subnautica.exp/UnityEngine.UI.dll
  Example mod/Mod.cs
  SMLHelper/Commands/ConsoleCommand.cs
  SMLHelper/Commands/ConsoleCommandAttribute.cs
  SMLHelper/Commands/Parameter.cs
  SMLHelper/Handlers/ConsoleCommandsHandler.cs
  SMLHelper/Initializer.cs
  SMLHelper/Interfaces/IConsoleCommandHandler.cs
  SMLHelper/Logger.cs
  SMLHelper/Options/Attributes/ButtonAttribute.cs
  SMLHelper/Options/Attributes/ChoiceAttribute.cs
  SMLHelper/Options/Attributes/IgnoreMemberAttribute.cs
  SMLHelper/Options/Attributes/KeybindAttribute.cs
  SMLHelper/Options/Attributes/MenuAttribute.cs
  SMLHelper/Options/Attributes/ModOptionAttribute.cs
  SMLHelper/Options/Attributes/ModOptionEventAttribute.cs
  SMLHelper/Options/Attributes/OnChangeAttribute.cs
  SMLHelper/Options/Attributes/OnGameObjectCreatedAttribute.cs
  SMLHelper/Options/Attributes/ToggleAttribute.cs
  SMLHelper/Patchers/ConsoleCommandsPatcher.cs
  SMLHelper/Patchers/DevConsolePatcher.cs
  SMLHelper/SMLHelper.csproj
Labels: Priority: Low, Type: Enhancement

#192 SMLHelper 2.9.0.1 HOTFIX: Revert default slider step
  Example mod/mod.json
  SMLHelper/Options/SliderModOption.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: High, Type: Bug
