Repository SubnauticaModding/Nautilus, pull requests merged in 2021-07, with the labels that each got.

#227 Protected Process Prefab fix
  SMLHelper/Assets/CustomFabricator.cs
Labels: Type: Bug

#229 Coordinated spawns hotfixes
  SMLHelper/Handlers/CoordinatedSpawnsHandler.cs
  SMLHelper/Json/Converters/QuaternionConverter.cs
  SMLHelper/Json/Converters/Vector3Converter.cs
  SMLHelper/MonoBehaviours/EntitySpawner.cs
  SMLHelper/Patchers/LargeWorldStreamerPatcher.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: High, Type: Bug

#230 SMLHelper 2.10.1
  SMLHelper/Handlers/CoordinatedSpawnsHandler.cs
  SMLHelper/Json/Converters/QuaternionConverter.cs
  SMLHelper/Json/Converters/Vector3Converter.cs
  SMLHelper/MonoBehaviours/EntitySpawner.cs
  SMLHelper/Patchers/LargeWorldStreamerPatcher.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: High, Type: Bug

#231 Menu options showing incorrect chosen value for enum-based `[Choice]` when using custom `string` names.
  SMLHelper/Options/Attributes/OptionsMenuBuilder.cs
Labels: Type: Bug

#232 Defer `ConfigFile` attribute-based events when using the `OptionsMenuBuilder` via `RegisterModOptions<ConfigFile>`.
  SMLHelper/Handlers/OptionsPanelHandler.cs
  SMLHelper/Options/Attributes/ConfigFileMetadata.cs
  SMLHelper/Options/Attributes/OptionsMenuBuilder.cs
Labels: Type: Maintenance

#234 `CoodinatedSpawnsInitialized.smlhelper` bugfix
  SMLHelper/Patchers/LargeWorldStreamerPatcher.cs
Labels: Priority: High, Type: Bug

#233 Add a base `JsonFile` implementation for extension, as well as a `SaveDataCache` extension of `JsonFile` for working with per-mod-per-saveslot cached data
  Example mod/Example mod.csproj
  Example mod/Mod.cs
  Example mod/mod.json
  SMLHelper/Handlers/IngameMenuHandler.cs
  SMLHelper/Handlers/SaveDataHandler.cs
  SMLHelper/Interfaces/IIngameMenuHandler.cs
  SMLHelper/Interfaces/ISaveDataHandler.cs
  SMLHelper/Json/Attributes/FileNameAttribute.cs
  SMLHelper/Json/ConfigFile.cs
  SMLHelper/Json/ConfigFileEventArgs.cs
  SMLHelper/Json/JsonFile.cs
  SMLHelper/Json/JsonFileEventArgs.cs
  SMLHelper/Json/SaveDataCache.cs
  SMLHelper/Patchers/IngameMenuPatcher.cs
  SMLHelper/SMLHelper.csproj
Labels: Type: Enhancement

#236 Add `Vector3Converter` and `QuaternionConverter` to `ConfigFile`
  SMLHelper/Json/ConfigFile.cs
Labels: Type: Enhancement

#235 SMLHelper 2.11
  Example mod/Example mod.csproj
  Example mod/Mod.cs
  Example mod/Properties/AssemblyInfo.cs
  Example mod/mod.json
  SMLHelper/Handlers/IngameMenuHandler.cs
  SMLHelper/Handlers/OptionsPanelHandler.cs
  SMLHelper/Handlers/SaveDataHandler.cs
  SMLHelper/Interfaces/IIngameMenuHandler.cs
  SMLHelper/Interfaces/ISaveDataHandler.cs
  SMLHelper/Json/Attributes/FileNameAttribute.cs
  SMLHelper/Json/ConfigFile.cs
  SMLHelper/Json/ConfigFileEventArgs.cs
  SMLHelper/Json/JsonFile.cs
  SMLHelper/Json/JsonFileEventArgs.cs
  SMLHelper/Json/SaveDataCache.cs
  SMLHelper/Options/Attributes/ConfigFileMetadata.cs
  SMLHelper/Options/Attributes/OptionsMenuBuilder.cs
  SMLHelper/Patchers/IngameMenuPatcher.cs
  SMLHelper/Patchers/LargeWorldStreamerPatcher.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/SMLHelper.csproj
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: High, Type: Bug, Type: Enhancement, Type: Maintenance

#239 SMLHelper 2.11.1: ConfigFile options menu hotfix
  Example mod/Properties/AssemblyInfo.cs
  SMLHelper/Options/Attributes/OptionsMenuBuilder.cs
  SMLHelper/Properties/AssemblyInfo.cs
  SMLHelper/mod_BelowZero.json
  SMLHelper/mod_Subnautica.json
Labels: Priority: High, Type: Bug
