Repository SubnauticaModding/Nautilus, pull requests merged in 2024-01, with the labels that each got.

#521 Prefab Requests are returned early
  Nautilus/Assets/ModPrefabRequest.cs
  Nautilus/Handlers/PrefabHandler.cs
Labels: Priority: Critical

#527 Hotfix: Use Fallback Node if targeted node not found.
  Nautilus/Patchers/CraftTreePatcher.cs
Labels: Priority: Critical, Type: Bug

#528 Stop Error Spam
  Nautilus/Patchers/CraftDataPatcher_Subnautica.cs
Labels: Priority: Low
